names:
- person
- car
- dog
- cat
- bicycle
- truck
- bird
- bus
- horse
- sheep
- cow
- elephant
- bear
- zebra
- giraffe
- backpack
- umbrella
- handbag
- tie
- suitcase
- frisbee
- skis
- snowboard
- sports_ball
- kite
- baseball_bat
- baseball_glove
- skateboard
- surfboard
- tennis_racket
- bottle
- wine_glass
- cup
- fork
- knife
- spoon
nc: 36
path: ''
test: test/Images
train: small/train/Images
val: val/Images
