names:
- aeroplane
- bicycle
- bird
- boat
- bottle
- bus
- car
- cat
- chair
- cow
- diningtable
- dog
- horse
- motorbike
- person_frontal
- person_jumping
- person_left
- person_other
- person_phoning
- person_playinginstrument
- person_reading
- person_rear
- person_ridingbike
- person_ridinghorse
- person_right
- person_running
- person_takingphoto
- person_unspecified
- person_usingcomputer
- person_walking
- pottedplant
- sheep
- sofa
- train
- tvmonitor
nc: 35
path: resized
test: test/images
train: small_train/images
val: val/images
